project:
  title: "r-interface"
  render:
    - "README.qmd"
    - "*.qmd"

execute:
  freeze: auto
author: "Aymeric Stamm"
title-block-banner: true
editor: visual

toc: true
number-sections: false

format:
  html: default
  gfm: default
